# Generated by Django 6.0.6 on 2026-06-24

from django.db import migrations



def backfill_mathematics_subject(apps, schema_editor):
    Subject = apps.get_model('core', 'Subject')
    Competency = apps.get_model('core', 'Competency')
    UserAccount = apps.get_model('core', 'UserAccount')

    mathematics = Subject.objects.filter(subject_name__iexact='Mathematics').first()
    if not mathematics:
        mathematics = Subject.objects.filter(subject_code='MATH').first()
    if not mathematics:
        mathematics = Subject.objects.create(subject_code='MATH', subject_name='Mathematics')

    unassigned = Competency.objects.filter(subject__isnull=True)
    creator_ids = list(unassigned.values_list('created_by_id', flat=True).distinct())
    unassigned.update(subject=mathematics)

    for account in UserAccount.objects.filter(user_id__in=creator_ids, role='Teacher'):
        account.subjects.add(mathematics)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_subject_useraccount_subjects_competency_subject'),
    ]

    operations = [
        migrations.RunPython(backfill_mathematics_subject, migrations.RunPython.noop),
    ]
