# Generated by Django 6.0.6 on 2026-06-24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_learnerprofile_created_by_and_optional_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_code', models.CharField(max_length=20, unique=True)),
                ('subject_name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['subject_name'],
            },
        ),
        migrations.AddField(
            model_name='useraccount',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='teachers', to='core.subject'),
        ),
        migrations.AddField(
            model_name='competency',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='competencies', to='core.subject'),
        ),
    ]
